### ISSUE TITLE
Make note-macro.list-builtin-commands less intrusive

### ISSUE THREAD

**Issue by jevakallio** [kneely/vscode-note-macros#2]
When executing the `Note macros: ...` commands, the "List all the commands..." seems quite intrusive -- I would not expect to see it every time I want to autocomplete "mac...". 

I couldn't immediately figure out how to use it. Was it intentionally published, or a debug command for development use?

I'd consider either removing it, or if it's necessary, giving it a more subtle name that does not have the "Note macros" prefix.

<img width="685" alt="Screenshot 2020-08-21 at 20 21 08" src="https://user-images.githubusercontent.com/1203949/89939989-be637d00-dc10-11ea-9b96-3510644e92e2.png">

**Comment by kneely** [comment]
@jevakallio this was intentionally left in. I thought it was a nice way to look at all available commands for your macros. I will rename it so it won't pop up every time. Thank you for your suggestion.

**Comment by kneely** [comment]
Fixed with commit [fd1a421](https://github.com/kneely/note-macros/commit/fd1a421be9a3828666c3754ecdd47643dc0b605f). 

Functionality is now "Macro Dev: List all the commands that can be used in macros"
